### PR TITLE
correct slo url

### PR DESCRIPTION
**Pull request by smotornyuk**

### CODE REVIEW

**Comment by MrkGrgsn** [comment]
@smotornyuk It looks like this PR got missed.  It looks obviously correct to match the latest config but we've not noted any bugs that would be related to this. Do you remember what the bug was or which Jira issue it was for?

**Comment by MrkGrgsn** [comment]
Is it for redirect after SP-initiated single logout?

**Comment by smotornyuk** [comment]
As i remember, we have no  ticket for this problem, this was just quick fix after change of BASE_URL in sp_config file. And yes, this should resolve some issue with redirect after logout

**Comment by MrkGrgsn** [comment]
I think this highlights an issue that should be resolved.  The SLO endpoint will depend on the pysaml config, this map should be set dynamically from that config. 

However, I think this should be merged anyway because we know that in our current version of this plugin, the SLO endpoint should be changed from the default to something like `/saml2/slo` to avoid conflicts with other POSTS. @smotornyuk if you update the included sp_config.py so that it includes default endpoints `/saml2/slo` and `/saml2/sso` then we can merge this.

**Comment by smotornyuk** [comment]
@MrkGrgsn , did you mean [this](https://github.com/DataShades/ckanext-saml2/blob/hotfix-of-after-login-redirect/ckanext/saml2/config/sp_config.py#L18-L19) ?

**Pull request closed without merging**
